### ISSUE TITLE
Is there a simple way to add this to path on windows?

### ISSUE THREAD

**Issue by s0py** [rakaly/cli#24]
Simple question. I know this is probably a general skill and not specific to this app but I think it would be good to link a tutorial in the readme.

**Comment by nickbabcock** [comment]
Yeah this is a good idea.

**Comment by nickbabcock** [comment]
Is it helpful for the readme to look like?

> - (optional): Add to your computers path for easier access
>   - For windows, PATH can be modified by [the GUI](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) or [the terminal](https://stackoverflow.com/q/9546324/433785)
